In [16]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

def flip_hori(img, mask):
    img = tf.image.flip_left_right(img)
    mask = tf.image.flip_left_right(mask)
    return img, mask

def flip_vert(img, mask):
    img = tf.image.flip_up_down(img)
    mask = tf.image.flip_up_down(mask)
    return img, mask

t1 = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
t2 = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(t1)
print(t2)
print("flip horizontal" , flip_hori(t1, t2))
print(flip_vert(t1, t2))

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(1, 3, 3), dtype=int32)
tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(1, 3, 3), dtype=int32)
flip horizontal (<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]]], dtype=int32)>, <tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]]], dtype=int32)>)
(<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>, <tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>)
